### PR TITLE
Tadhg/ar

### PR DESCRIPTION
**Pull request by tadhgryan2012**
Here's AR, not the greatest but she works

### CODE REVIEW

**Review by CraigPhayer — APPROVED** [review]
Anything with my name on it looks all good :)

**Review by Bojo992 — APPROVED** [review]
XdMemeGIF

**Review by s1m0nWasTaken — APPROVED** [review]
Good work !

**Comment by M-Byte480** [comment]
image

**Review by M-Byte480 — APPROVED** [review]

**Review by BrenyQT — APPROVED** [review]
Savage

**Pull request merged**
